version: 2.1

orbs:
  windows: circleci/windows@4.1.1
  python: circleci/python@2.0.3

jobs:
  build-and-test-stable:
    executor:
      name: windows/default
      shell: powershell.exe
    steps:
      - checkout
      # upgrade
      - run:
          command: pip install --upgrade --user pip setuptools wheel
          name: pip install --upgrade --user pip setuptools wheel
      # pip require package
      - run:
          command: pip install --user -r requirements.txt
          name: pip requirements.txt
      # run on shell test
      - run:
          command: python ./test/unit_test/exec/shell_exec_test/shell_test.py
          name: shell_test
      # save and open file test
      - run:
          command: python ./test/unit_test/file/save_and_open/save_and_open.py
          name: save_and_open_test
      # open and close editor
      - run:
          command: python ./test/unit_test/tkinter_test/editor/editor_with_theme.py
          name: open_and_close_editor

  build-and-test-dev:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      # upgrade
      - run:
          command: pip install --upgrade --user pip setuptools wheel
          name: pip install --upgrade --user pip setuptools wheel
      # pip require package
      - run:
          command: pip install --user -r dev_requirements.txt
          name: pip requirements.txt
      # run on shell test
      - run:
          command: python ./test/unit_test/exec/shell_exec_test/shell_test.py
          name: shell_test
      # save and open file test
      - run:
          command: python ./test/unit_test/file/save_and_open/save_and_open.py
          name: save_and_open_test



workflows:
  main:
    jobs:
      - build-and-test-dev
      - build-and-test-stable:
          requires:
            - build-and-test-dev
