version: 2.1

orbs:
  windows: circleci/windows@4.1.1
  python: circleci/python@2.0.3

jobs:
  build-and-test-stable:
    executor:
      name: windows/default
      shell: powershell.exe
    steps:
      - checkout
      # upgrade
      - run:
          command: pip install --upgrade --user pip setuptools wheel
          name: pip install --upgrade --user pip setuptools wheel
      # pip require package
      - run:
          command: pip install --user -r requirements.txt
          name: pip requirements.txt

  build-and-test-dev:
    executor:
      name: windows/default
      shell: powershell.exe
    steps:
      - checkout
      # upgrade
      - run:
          command: pip install --upgrade --user pip setuptools wheel
          name: pip install --upgrade --user pip setuptools wheel
      # pip require package
      - run:
          command: pip install --user -r dev_requirements.txt
          name: pip requirements.txt

workflows:
  main:
    jobs:
      - build-and-test-dev
      - build-and-test-stable:
          requires:
            - build-and-test-dev
